### ISSUE TITLE
패들 위치 초기화 안되는 이슈 - 라운드 마다 초기화가 안된다. 

### ISSUE THREAD

**Issue by tg201005** [trancendering/ft_transcendence#72]
### Issue Type

- [ ] Bug (오류)
- [ ] Feature Request (기능 요청)
- [ ] Performance (성능 문제)
- [ ] UI/Design (UI/디자인 관련)
- [ ] Documentation (문서 관련)
- [ ] Enhancement (개선 제안)
- [ ] Other - Please Describe:

### Priority

- [ ] Critical
- [ ] High
- [ ] Medium
- [ ] Low

### Steps to Reproduce

1.
2.
3.

### Environment

- Operating System:
- Browser (if applicable):
- Version:

**Comment by gerry-mandering** [comment]
hyeyukim님이 수정 완료!
